"""Generate a page-overlay demo AFP (BMO/EMO overlay included via IPO).

Usage:
    python tools/make_overlay_sample.py [output_path]

Builds a one-page document whose page body text sits on top of a reusable
overlay (a letterhead title, a rule under it, and a footer). The overlay
is defined once in a resource group and pulled onto the page with a single
Include Page Overlay (IPO) field — the way AFP shares forms and letterhead
across many pages.
"""

import struct
import sys
from pathlib import Path

UPI = 1440
PAGE_W = 12240   # 8.5 in
PAGE_H = 15840   # 11 in

# PTOCA control-sequence function types (unchained/even values).
AMI, AMB, TRN, STC, DIR, SCFL = 0xC6, 0xD2, 0xDA, 0x74, 0xE4, 0xF0
BLUE, BLACK = 0x0001, 0x0008  # STC standard color values


def _sf(sf_id: int, data: bytes = b"") -> bytes:
    body = sf_id.to_bytes(3, "big") + b"\x00\x00\x00" + data
    return b"\x5a" + struct.pack(">H", len(body) + 2) + body


def _name(s: str) -> bytes:
    """8-byte EBCDIC token name (how MO:DCA stores Begin-field names)."""
    return s.encode("cp500")[:8].ljust(8, b"\x40")


def _ptx(*seqs) -> bytes:
    """Assemble a PTX control-sequence chain from (type, params) pairs."""
    out = bytearray(b"\x2b\xd3")
    for i, (t, p) in enumerate(seqs):
        chained = 1 if i < len(seqs) - 1 else 0
        out += bytes([2 + len(p), t | chained]) + p
    return bytes(out)


def _move(x: int, y: int):
    return (AMI, struct.pack(">H", x)), (AMB, struct.pack(">H", y))


def _text(s: str):
    return (TRN, s.encode("cp500"))


def _color(v: int):
    return (STC, struct.pack(">H", v))


def _rule(length: int, thickness: int):
    return (DIR, struct.pack(">hh", length, thickness))


def _pgd() -> bytes:
    xu = UPI * 10
    return b"\x00\x00" + struct.pack(">HH", xu, xu) + PAGE_W.to_bytes(
        3, "big"
    ) + PAGE_H.to_bytes(3, "big")


def _overlay() -> bytes:
    body = _ptx(
        _color(BLUE), *_move(720, 760),
        _text("ACME ASSURANCE  -  Policyholder Services"),
        _color(BLACK), *_move(720, 900), _rule(10800, 40),
        *_move(720, 15200), _rule(10800, 20),
        *_move(720, 15480),
        _text("Generated by readAFP - AFP page-overlay demo"),
    )
    return (
        _sf(0xD3A8DF, _name("LETTERHD"))          # BMO
        + _sf(0xD3A8C9)                     # BAG
        + _sf(0xD3A6AF, _pgd())             # PGD
        + _sf(0xD3A9C9)                     # EAG
        + _sf(0xD3A89B)                     # BPT
        + _sf(0xD3EE9B, body)               # PTX
        + _sf(0xD3A99B)                     # EPT
        + _sf(0xD3A9DF, _name("LETTERHD"))        # EMO
    )


def _ipo(name: str, x: int = 0, y: int = 0) -> bytes:
    return name.encode("cp500")[:8].ljust(8, b"\x40") + x.to_bytes(
        3, "big", signed=True
    ) + y.to_bytes(3, "big", signed=True)


def build_afp() -> bytes:
    body = _ptx(
        _color(BLACK),
        *_move(900, 1760), _text("Dear Policyholder,"),
        *_move(900, 2360),
        _text("The letterhead, rule, and footer on this page are not part"),
        *_move(900, 2960),
        _text("of the page itself - they live in a reusable AFP overlay"),
        *_move(900, 3560),
        _text("(BMO/EMO), pulled in with one Include Page Overlay field."),
        *_move(900, 4160),
        _text("readAFP composites the overlay beneath this body text."),
    )
    return (
        _sf(0xD3A8A8, _name("OVLYDEMO"))          # BDT
        + _sf(0xD3A8C6, b"RESGRP\x00\x00")  # BRG
        + _overlay()
        + _sf(0xD3A9C6, b"RESGRP\x00\x00")  # ERG
        + _sf(0xD3A8AF)                     # BPG
        + _sf(0xD3A8C9)                     # BAG
        + _sf(0xD3A6AF, _pgd())             # PGD
        + _sf(0xD3A9C9)                     # EAG
        + _sf(0xD3AFD8, _ipo("LETTERHD"))   # IPO (include the overlay)
        + _sf(0xD3A89B)                     # BPT
        + _sf(0xD3EE9B, body)               # PTX
        + _sf(0xD3A99B)                     # EPT
        + _sf(0xD3A9AF)                     # EPG
        + _sf(0xD3A9A8, _name("OVLYDEMO"))        # EDT
    )


if __name__ == "__main__":
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(
        "testdata/overlay_sample.afp"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    data = build_afp()
    out.write_bytes(data)
    print(f"Wrote {len(data):,} bytes -> {out}")
